# Default values for tfm-almacar application.
# Declare variables to be passed into your templates.

global:
  kafka:
    host: tfm-almacar-kafka
    port: 9092
  dal:
    host: tfm-almacar-dal
    port: 50057
    jvm:
      startheapmemory: 128m
      maxheapmemory: 256m
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  mysql:
    host: tfm-almacar-mysql
    port: 3306
  stockchecker:
    threshold: 2
    rest:
      host: localhost
      port: 8082
      endpoint: order
    jvm:
      startheapmemory: 128m
      maxheapmemory: 256m
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  restapi:
    jvm:
      startheapmemory: 128m
      maxheapmemory: 256m
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

kafka:
  headless:
    port: 9092
  replicas: 1
  configurationOverrides:
    "offsets.topic.replication.factor": 1
  #external:
    #enabled: True
    #servicePort: '19092'
  zookeeper:
    replicaCount: 1

restapi:
  replicaCount: 1
  service:
    type: NodePort
    port: 8080

dal:
  replicaCount: 1

stockchecker:
  replicaCount: 1
