# Default values for tfm-almacar application.
# Declare variables to be passed into your templates.

global:
  kafka:
    host: tfm-almacar-kafka
    port: 9092
  dal:
    host: tfm-almacar-dal
    port: 50057
    portmetrics: 8080
    jvm:
      startheapmemory: 128m
      maxheapmemory: 256m
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  mysql:
    host: tfm-almacar-mysql
    port: 3306
  stockchecker:
    threshold: 2
    host: tfm-almacar-stockchecker
    port: 8080
    rest:
      host: localhost
      port: 8082
      endpoint: order
    jvm:
      startheapmemory: 128m
      maxheapmemory: 256m
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  restapi:
    jvm:
      startheapmemory: 128m
      maxheapmemory: 256m
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

kafka:
  headless:
    port: 9092
  replicas: 1
  configurationOverrides:
    "offsets.topic.replication.factor": 1
  #external:
    #enabled: True
    #servicePort: '19092'
  zookeeper:
    replicaCount: 1

restapi:
  replicaCount: 1
  service:
    type: NodePort
    port: 8080

dal:
  replicaCount: 1

stockchecker:
  replicaCount: 1

prometheus-operator:
  prometheus:
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: 'prometheus'
          scrape_interval: 1m
          static_configs:
            - targets: ['localhost:9090']
        - job_name: 'restapi-service'
          scrape_interval: 1m
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ['tfm-almacar-restapi:8080']
        - job_name: 'stockchecker-service'
          scrape_interval: 1m
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ['tfm-almacar-stockchecker:8080']
        - job_name: 'dal-service'
          scrape_interval: 1m
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ['tfm-almacar-dal:8080']
        - job_name: 'grafana'
          scrape_interval: 1m
          metrics_path: '/metrics'
          static_configs:
            - targets: ['tfm-almacar-grafana:3000']
  grafana:
    adminPassword: 'adminadmin'

