# Default values for tfm-almacar application.
# Declare variables to be passed into your templates.

global:
  var1: value1

# Kafka configuration
kafka:
  replicas: 1
  configurationOverrides:
    "offsets.topic.replication.factor": 1
  #external:
    #enabled: True
    #servicePort: '19092'
  zookeeper:
    replicaCount: 1
