apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dal.fullname" . }}
    app.kubernetes.io/component: {{ include "dal.fullname" . }}
    app.kubernetes.io/part-of: {{ .Values.global.appname }}
    {{- range .Values.global.labels }}
    {{ .name }}: {{ .value }}
    {{- end }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dal.fullname" . }}
      app.kubernetes.io/component: {{ include "dal.fullname" . }}
      app.kubernetes.io/part-of: {{ .Values.global.appname }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dal.fullname" . }}
        app.kubernetes.io/component: {{ include "dal.fullname" . }}
        app.kubernetes.io/part-of: {{ .Values.global.appname }}
    spec:
      initContainers:
      - name: init-mysql
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup {{ .Release.Name }}-mysql; do echo waiting for myservice; sleep 2; done;"]
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.global.dal.port }}
        - containerPort: {{ .Values.global.dal.portmetrics }}
        env:
        - name: JAVA_OPTS
          value: "-Xmx{{ .Values.global.restapi.jvm.maxheapmemory }} -Xms{{ .Values.global.restapi.jvm.startheapmemory }}"
        resources:
          requests:
            memory: "{{ .Values.global.dal.resources.requests.memory }}"
            cpu: "{{ .Values.global.dal.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.global.dal.resources.limits.memory }}"
            cpu: "{{ .Values.global.dal.resources.limits.cpu }}"