apiVersion: v1
kind: Service
metadata:
  name: {{ include "dal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dal.fullname" . }}-service
    app.kubernetes.io/component: {{ include "dal.fullname" . }}
    app.kubernetes.io/part-of: {{ .Values.global.appname }}
    {{- range .Values.global.labels }}
    {{ .name }}: {{ .value }}
    {{- end }}
spec:
  selector:
    app: {{ include "dal.fullname" . }}
  ports:
  - port: {{ .Values.dal.port }}
