# Default values for restapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: almacar_restapi
  tag: 0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080