server:
  port: 8080

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:19092
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json
