apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "restapi.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "restapi.fullname" . }}
    app.kubernetes.io/component: {{ include "restapi.fullname" . }}
    app.kubernetes.io/part-of: {{ .Values.global.appname }}
    {{- range .Values.global.labels }}
    {{ .name }}: {{ .value }}
    {{- end }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "restapi.fullname" . }}
      app.kubernetes.io/component: {{ include "restapi.fullname" . }}
      app.kubernetes.io/part-of: {{ .Values.global.appname }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "restapi.fullname" . }}
        app.kubernetes.io/component: {{ include "restapi.fullname" . }}
        app.kubernetes.io/part-of: {{ .Values.global.appname }}
    spec:
      initContainers:
      - name: init-kafka
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup {{ .Release.Name }}-kafka; do echo waiting for myservice; sleep 2; done;"]
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"


