apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "restapi.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "restapi.fullname" . }}
          servicePort: {{ .Values.service.port }}
