# Default values for stockchecker.
# Declare variables to be passed into your templates.

stockchecker:
  replicaCount: 1

  image:
    repository: almacar_stockchecker
    tag: 0.1
    pullPolicy: IfNotPresent
