# Default values for stockchecker.
# Declare variables to be passed into your templates.

global:
  kafka:
    host: kafka
    port: 9092
  dal:
    host: dal
    port: 50057

replicaCount: 1

image:
  repository: almacar_stockchecker
  tag: 0.1
  pullPolicy: IfNotPresent
