# Default values for stockchecker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  kafka:
    host: kafka
    port: 9092
  dal:
    host: dal
    port: 50057
  stockchecker:
    threshold: 2
    rest:
      host: localhost
      port: 8082
      endpoint: order

replicaCount: 1

image:
  repository: almacar_stockchecker
  tag: 0.1
  pullPolicy: IfNotPresent

service:
  threshold: 2
