spring:
  application:
    name: stockchecker
stockchecker:
  threshold: 2
  rest:
    host: localhost
    port: 8080
    endpoint: order
dal:
  host: dal
  port: 50051
kafka:
  bootstrap-servers: kafka:9092
  topic:
    json: mytopic
